name: Build for Linux

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir pyzipper requests pyinstaller PySimpleGUI

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --clean --console --distpath ./dist --workpath ./build src/main.py

      - name: Check Artifacts
        run: ls -R ./dist

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: minecraft-mods-localizer-macos
          path: ./dist/
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build --no-cache -f ./linux/Dockerfile -t pyinstaller-linux .

      - name: Run Docker container
        id: run-container
        run: |
          docker run --rm -v $(pwd)/src:/src -v $(pwd)/linux:/linux \
              pyinstaller-linux pyinstaller main.py \
              --onedir --onefile --clean --console \
              --distpath /linux/dist \
              --workpath /linux/build \
              --specpath /linux 

      - name: Check Artifacts
        run: ls -R ./linux/dist

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: minecraft-mods-localizer-linux
          path: ./linux/dist/main

