name: Build for Linux

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build --no-cache -f ./linux/Dockerfile -t pyinstaller-linux .  # --no-cacheを追加しました

      - name: Run Docker container
        id: run-container
        run: |
          docker run --rm -v $(pwd)/src:/src -v $(pwd)/linux:/linux \
              pyinstaller-linux pyinstaller main.py \
              --onedir --onefile --clean --console \
              --distpath /linux/dist \
              --workpath /linux/build \
              --specpath /linux 

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: result-artifact
          path: ./linux/dist/main
