name: Build for Linux

on:
  push:
    branches:
      - 'dev'

jobs:
  build-linux:
    runs-on: linux-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build --no-cache -f ./linux/Dockerfile -t pyinstaller-linux .

      - name: Create dist directory
        run: mkdir -p linux/dist

      - name: Run Docker container
        run: docker run --rm -v "${{ github.workspace }}/linux/dist:/dist" \
          pyinstaller-linux pyinstaller main.py \
          --onedir --onefile --clean --console \
          --distpath /dist \
          --workpath /build \
          --specpath /

      - name: Check Artifacts
        run: ls -R ./linux/dist

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: minecraft-mods-localizer-linux
          path: ./linux/dist/main

