name: Build for Linux

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build --no-cache -f ./linux/Dockerfile -t pyinstaller-linux .

      - name: Run Docker container
        id: run-container
        run: |
          docker run --rm -v $(pwd)/src:/src -v $(pwd)/linux:/linux \
              pyinstaller-linux pyinstaller main.py \
              --onedir --onefile --clean --console \
              --distpath /linux/dist \
              --workpath /linux/build \
              --specpath /linux 

      - name: Check Artifacts
        run: ls -R ./linux/dist  # This step will help verify if the artifacts are generated correctly

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: minecraft-mods-localizer-linux
          path: ./linux/dist/main  # Make sure this path is correct based on your build script

