name: Build for macOS

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'  # Specify the Python version, or '3.x' for the latest

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir pyzipper requests pyinstaller PySimpleGUI

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --clean --console --distpath ./dist --workpath ./build src/main.py

      - name: Check Artifacts
        run: ls -R ./dist  # This will list the contents of the dist directory, helping verify if the build artifacts are generated correctly.

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: minecraft-mods-localizer-macos
          path: ./dist/  # Or specify the exact file you want to upload, e.g., ./dist/main if "main" is the output binary