name: Release Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    needs:
      - build_for_linux
      - build_for_macos
      - build_for_windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact for Windows
        uses: actions/download-artifact@v2
        with:
          name: minecraft-mods-localizer-windows
          path: artifacts/windows

      - name: Download artifact for MacOS
        uses: actions/download-artifact@v2
        with:
          name: minecraft-mods-localizer-macos
          path: artifacts/macos

      - name: Download artifact for Linux
        uses: actions/download-artifact@v2
        with:
          name: minecraft-mods-localizer-linux
          path: artifacts/linux

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Description of the release
          draft: false
          prerelease: false

      - name: Upload Release Asset for Windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/windows
          asset_name: minecraft-mods-localizer-windows.zip
          asset_content_type: application/zip

      - name: Upload Release Asset for MacOS
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/macos
          asset_name: minecraft-mods-localizer-macos.zip
          asset_content_type: application/zip

      - name: Upload Release Asset for Linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/linux
          asset_name: minecraft-mods-localizer-linux.zip
          asset_content_type: application/zip
