name: Build for Windows

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: windows-2019

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -f ./windows/Dockerfile -t pyinstaller-windows .

      - name: Create dist directory
        run: mkdir windows\dist

      - name: Run Docker container
        run: docker run --rm -v "${{ github.workspace }}\windows\dist:C:\dist" pyinstaller-windows powershell -Command "pyinstaller main.py --onedir --onefile --clean --console --distpath C:\dist --workpath C:\build --specpath C:\"

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: minecraft-mod-localizer-windows
          path: windows/dist/main.exe
